In [19]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('test-data.csv')
data = data.iloc[:, 1:]
data.head()
# plt.scatter(data.Hours, data.Scores)
# plt.show()

# def loss_function(m, b, points):
#   total_error = 0
  
#   for i in range(len(points)):
#     X = points.iloc[i].Hours
#     Y = points.iloc[i].Scores
#     total_error += (Y - (m * X + b)) ** 2

#   total_error / float(len(points))
#   return total_error

# def gradient_descent(m_now, b_now, points, L):
#   m_gradient = 0
#   b_gradient = 0

#   n = len(points)
  
#   for i in range(n):
#     X = points.iloc[i].Hours
#     Y = points.iloc[i].Scores

#     m_gradient += -(2/n) * X * (Y - (m_now * X + b_now))
#     b_gradient += -(2/n) * (Y - (m_now * X + b_now))

#   m = m_now - m_gradient * L
#   b = b_now - b_gradient * L

#   return m, b


# m = 0
# b = 0
# L = 0.0001
# epochs = 300

# for i in range(epochs):
#   m, b = gradient_descent(m, b, data, L)

# print(m, b)

# print(type(data.Hours))

# plt.scatter(data.Hours, data.Scores, color="black")
# plt.plot(list(range(0, 10)), [m * X + b for X in range(0, 10)], color="red")
# plt.show()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN